name       : zsxd
version    : 1.12.2
release    : 4
source     :
    - https://gitlab.com/solarus-games/zsxd/-/archive/v1.12.2/zsxd-v1.12.2.tar.bz2 : 656ac2033db2aca7ad0cd5c7abb25d88509b312b155ab83546c90abbc8583df1
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : games.rpg
summary    : Zelda - Mystery of Solarus XD - This is a parody of Mystery of Solarus DX
description: |
    Zelda - Mystery of Solarus XD - This is a parody of Mystery of Solarus DX
rundeps    :
    - solarus
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    for i in 16 24 32 48 64 128 256 512 1024; do \
        install -D -m 00644 data/logos/icon_$i.png $installdir/usr/share/icons/hicolor/"$i"x"$i"/apps/zsxd.png; \
    done
    install -D -m 00644 $pkgfiles/zsxd.desktop $installdir/usr/share/applications/zsxd.desktop
